---
dist: bioinic
sudo: required
before_install:
  - |
    sudo apt-get -y install \
      texlive-latex-base \
      texlive-latex-extra \
      texlive-extra-utils \
      texlive-fonts-recommended
addons:
  apt:
    update: true
script:
  - cd applsci-915286-done && pdflatex applsci-915286-done.tex
